# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# vulnerability scan with Anchore's Grype tool, and integrates the results with GitHub Advanced Security
# code scanning feature.  For more information on the Anchore scan action usage
# and parameters, see https://github.com/anchore/scan-action. For more
# information on Anchore's container image scanning tool Grype, see
# https://github.com/anchore/grype
name: Anchore Container Scan

on:
  push:
    branches: [ main ]


jobs:
  Anchore-Build-Scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
      uses: anchore/sbom-action@v0.7.0
      with:
        image: ghcr.io/bananth2008/signedcontainer:1910545656
        registry-username: bananth2008
        registry-password: ${{secrets.GITHUB_TOKEN}}
  
  Provenance-Generation:
    needs: Anchore-Build-Scan
    runs-on: ubuntu-latest
    name: Generate Build Provenance
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
      
      - name: Generate Provinenace
        uses: slsa-framework/github-actions-demo@v0.1
        
          
      - name: Upload Provenance
        uses: actions/upload-artifact@v3
        with:
          path: build.provenance
      
      
    
    
    
        
